name: "Service Mesh Pattern Testing with Meshery"
description: "Importing Pattern to Meshery"
author: "Layer5"
inputs:
  provider_token:
    description: "Provider token to use. NOTE: value of the 'token' key in auth.json"
  service_mesh:
    # used for provisioning appropriate meshery-adatper
    description: "Service mesh to use. e.g: osm, istio etc"
    required: true
  platform:
    description: "Platform to deploy meshery on. Possible values: docker, kubernetes"
    default: docker
  url:
    description: "A raw Github URL for the patterns to be deployed"
    default: https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/IstioFilterPattern.yaml
runs:
  using: "node12"
  main: "main.js"
branding:
  icon: 'check-circle'
  color: 'green'